#!/usr/bin/env python3
import argparse
import struct
import sys
from pathlib import Path


ICON_COUNT = 4
ICON_W = 16
ICON_H = 16


def rgb_to_ds(rr, gg, bb):
    r5 = (rr * 31) // 255
    g5 = (gg * 31) // 255
    b5 = (bb * 31) // 255
    return 0x8000 | (b5 << 10) | (g5 << 5) | r5


def read_bmp(path):
    data = Path(path).read_bytes()
    if len(data) < 54 or data[:2] != b"BM":
        raise ValueError(f"{path}: not a BMP file")

    pixel_off = struct.unpack_from("<I", data, 10)[0]
    dib_size = struct.unpack_from("<I", data, 14)[0]
    width = struct.unpack_from("<i", data, 18)[0]
    height = struct.unpack_from("<i", data, 22)[0]
    planes = struct.unpack_from("<H", data, 26)[0]
    bpp = struct.unpack_from("<H", data, 28)[0]
    compression = struct.unpack_from("<I", data, 30)[0]

    if dib_size != 40 or width != ICON_W or abs(height) != ICON_H:
        raise ValueError(f"{path}: expected a {ICON_W}x{ICON_H} BITMAPINFOHEADER BMP")
    if planes != 1 or bpp not in (4, 24, 32) or compression != 0:
        raise ValueError(f"{path}: expected uncompressed 4bpp, 24bpp or 32bpp BMP")

    palette = []
    if bpp == 4:
        palette_bytes = pixel_off - 14 - dib_size
        if palette_bytes <= 0 or palette_bytes % 4:
            raise ValueError(f"{path}: invalid palette")
        palette_count = palette_bytes // 4
        for idx in range(palette_count):
            bb, gg, rr, _ = struct.unpack_from("<BBBB", data, 14 + dib_size + idx * 4)
            palette.append(rgb_to_ds(rr, gg, bb))

    stride = ((ICON_W * bpp + 31) // 32) * 4
    pixels = []
    for y in range(ICON_H):
        source_y = ICON_H - 1 - y if height > 0 else y
        row_off = pixel_off + source_y * stride
        row = data[row_off:row_off + stride]
        if len(row) < stride:
            raise ValueError(f"{path}: truncated pixel data")
        for x in range(ICON_W):
            if bpp == 4:
                packed = row[x // 2]
                color_idx = packed >> 4 if (x & 1) == 0 else packed & 0x0f
                if color_idx >= len(palette):
                    raise ValueError(f"{path}: palette index {color_idx} out of range")
                pixels.append(palette[color_idx])
            else:
                bytes_per_pixel = bpp // 8
                bb, gg, rr = row[x * bytes_per_pixel:x * bytes_per_pixel + 3]
                pixels.append(rgb_to_ds(rr, gg, bb))
    return pixels


def write_header(path):
    Path(path).write_text(
        "#pragma once\n"
        "#include \"types.h\"\n\n"
        "#define SIGNAL_ICON_W 16\n"
        "#define SIGNAL_ICON_H 16\n"
        "#define SIGNAL_ICON_COUNT 4\n"
        "#define SIGNAL_ICON_PIXELS (SIGNAL_ICON_W * SIGNAL_ICON_H)\n\n"
        "extern const u16 g_signalIcons[SIGNAL_ICON_COUNT][SIGNAL_ICON_PIXELS];\n",
        encoding="utf-8",
        newline="\n",
    )


def write_source(path, icons):
    lines = [
        "/* Generated by buildtools/build_signal_icons.py. Do not edit. */",
        "#include \"signal_icons.h\"",
        "",
        "const u16 g_signalIcons[SIGNAL_ICON_COUNT][SIGNAL_ICON_PIXELS] = {",
    ]
    for icon in icons:
        lines.append("    {")
        for row in range(ICON_H):
            values = icon[row * ICON_W:(row + 1) * ICON_W]
            lines.append("        " + ", ".join(f"0x{value:04x}" for value in values) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--out-c", required=True)
    parser.add_argument("--out-h", required=True)
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    icons = [read_bmp(input_dir / f"{idx}.bmp") for idx in range(1, ICON_COUNT + 1)]
    Path(args.out_c).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_h).parent.mkdir(parents=True, exist_ok=True)
    write_header(args.out_h)
    write_source(args.out_c, icons)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, struct.error) as exc:
        print(f"{Path(__file__).name}: error: {exc}", file=sys.stderr)
        raise SystemExit(1)
